# Generated by Django 4.2 on 2023-05-13 16:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_bill_file_alter_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
