# Generated by Django 4.2 on 2023-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_inquiry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_roommates',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
