# Generated by Django 4.2 on 2023-05-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_customuser_preferred_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
