# Generated by Django 4.2 on 2023-05-24 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_contract_price_suggested_by_contract_suggested_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='price_suggested_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='suggested_price',
        ),
        migrations.CreateModel(
            name='SuggestedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('price_suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
