# Generated by Django 4.2 on 2023-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_inquiry_options_inquiry_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('rent', 'Rent'), ('other', 'Other'), ('deposits_guarantees', 'deposits_guarantees')], max_length=20),
        ),
    ]
