# Generated by Django 4.2 on 2023-05-29 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='User who paid the bill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when the bill was paid.', null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
